"use client";
import Head from "next/head";
import { faSearch } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Product } from "@/components/ProductItem";

const fetchData = async (url: string) => {
  const data = await fetch(url).then((res) => res.json());
  return data;
};

export default function Shop() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const query = searchParams.get("q");
  const gender = searchParams.get("gender");
  const [productsData, setProducts] = useState<Product[]>([]);
  const [searchValue, setSearchValue] = useState<{ product: string }>({
    product: "",
  });

  const fetchProducts = async () => {
    const data = await fetchData("http://localhost:5001/products");
    setProducts(data);
    if (gender === "man") {
      const man = await fetchData("http://localhost:5001/products?gender=man");
      setProducts(man);
    } else if (gender === "women") {
      const women = await fetchData(
        "http://localhost:5001/products?gender=women"
      );
      setProducts(women);
    }
  };

  useEffect(() => {
    fetchProducts();
  }, []);

  const onSubmitValue = async () => {
    const querySearch = await fetchData(
      `http://localhost:5001/products?q=${searchValue.product}`
    );
    router.push(`/shop?q=${searchValue.product}`);
    setProducts(querySearch);

    if (gender === "women" || gender === "man") {
      const genderParam = gender === "women" ? "women" : "man";
      router.push(`/shop?gender=${genderParam}&q=${searchValue.product}`);
      const prductsByQueryParams = await fetchData(
        `http://localhost:5001/products?gender=${genderParam}&q=${searchValue.product}`
      );
      setProducts(prductsByQueryParams);
    }
    setSearchValue({ product: searchValue.product });
  };

  const onClickValue = async (param: string, value: string, query: string) => {
    let filterQuery;
    if (query) {
      filterQuery = await fetchData(
        `http://localhost:5001/products${
          param + value + query + searchValue.product
        }`
      );
      router.push(`${param + value + query + searchValue.product}`);
      setProducts(filterQuery);
    } else {
      filterQuery = await fetchData(
        `http://localhost:5001/products${param + value}`
      );
      router.push(param + value);
      setProducts(filterQuery);
    }
  };

  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg0 m-t-23 p-b-140">
        <div className="container">
          <div className="flex-w flex-sb-m p-b-52">
            <div className="flex-w flex-l-m filter-tope-group m-tb-10">
              <button
                className="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5 how-active1"
                onClick={() => onClickValue("?", "", "")}
              >
                All Products
              </button>

              <button
                className="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5"
                onClick={() =>
                  onClickValue("?gender=", "women", `${!query ? "" : "&q="}`)
                }
              >
                Women
              </button>

              <button
                className="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5"
                onClick={() =>
                  onClickValue("?gender=", "man", `${!query ? "" : "&q="}`)
                }
              >
                Men
              </button>

              <button
                className="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5"
                onClick={() => onClickValue("?q=", "belt", "")}
              >
                Belt
              </button>

              <button
                className="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5"
                onClick={() => onClickValue("?q=", "shoes", "")}
              >
                Shoes
              </button>

              <button
                className="stext-106 cl6 hov1 bor3 trans-04 m-r-32 m-tb-5"
                onClick={() => onClickValue("?q=", "watch", "")}
              >
                Watches
              </button>
            </div>

            <div className="flex-w flex-c-m m-tb-10">
              <div
                onClick={onSubmitValue}
                className="flex-c-m stext-106 cl6 size-105 bor4 pointer hov-btn3 trans-04 m-tb-4 js-show-search show-search"
              >
                Search
              </div>
            </div>

            {/* search */}
            <div className="panel-search w-full p-t-10 p-b-15">
              <div className="bor8 dis-flex p-l-15">
                <button className="size-113 flex-c-m fs-16 cl2 hov-cl1 trans-04">
                  <div className="icon-shop-item">
                    <FontAwesomeIcon icon={faSearch} />
                  </div>
                </button>

                <input
                  className="mtext-107 cl2 size-114 plh2 p-r-15"
                  type="text"
                  name="search"
                  placeholder="Search"
                  onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                    setSearchValue({ product: e.target.value })
                  }
                  value={searchValue.product}
                />
              </div>
            </div>
          </div>

          <div className="row isotope-grid">
            {productsData.length > 0 ? (
              productsData?.map((item: any) => {
                return (
                  <div
                    key={item.id}
                    className="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item women"
                  >
                    <div className="block2">
                      <div className="block2-pic hov-img0">
                        <img src={item.img} alt="IMG-PRODUCT" />

                        <Link
                          href={`/shop/${item.id}`}
                          className="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04 js-show-modal1"
                        >
                          View Details
                        </Link>
                      </div>

                      <div className="block2-txt flex-w flex-t p-t-14">
                        <div className="block2-txt-child1 flex-col-l ">
                          <a
                            href="product-detail.html"
                            className="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6"
                          >
                            {item.title}
                          </a>

                          <span className="stext-105 cl3">{item.price}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })
            ) : (
              <p>Three are no results!</p>
            )}
          </div>

          <div className="flex-l-m flex-w w-full p-t-10 m-lr--7">
            <a
              href="#"
              className="flex-c-m how-pagination1 trans-04 m-all-7 active-pagination1"
            >
              1
            </a>

            <a href="#" className="flex-c-m how-pagination1 trans-04 m-all-7">
              2
            </a>

            <a href="#" className="flex-c-m how-pagination1 trans-04 m-all-7">
              3
            </a>
          </div>
        </div>
      </div>
    </>
  );
}
